## Numpay Basics:

In [2]:
import numpy as np

In [3]:
#2-D array
arr2 = np.array([[1,2,3], [4,5,6]])
print("2D array:\n",arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


In [6]:
#sms2:
arr_a = np.array([1,2,3])
arr_b = np.array([4,8,56])

print("The addition:",arr_a+arr_b)
print("The multiplication:",arr_a*arr_b)
print("The square of arr_a:",arr_a**2)
print("The square of arr_b:",arr_b**2)

The addition: [ 5 10 59]
The multiplication: [  4  16 168]
The square of arr_a: [1 4 9]
The square of arr_b: [  16   64 3136]


In [19]:
#Reshaping
reshaped = np.arange(12).reshape(3,4)
print("Reshaped(3X4):\n\n",reshaped)

Reshaped(3X4):

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Numpy Useful Functions:

In [23]:
arr = np.array([23,5,56,11,1,32])
print("Mean:",np.mean(arr))

Mean: 21.333333333333332


In [24]:
print("Standard deviation:",np.std(arr))

Standard deviation: 18.732028424302822


In [25]:
print("Sorted:",np.sort(arr))

Sorted: [ 1  5 11 23 32 56]


In [4]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("(5X5):\n\n",mat)

(5X5):

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [5]:
sum_mat = np.sum(mat,axis = 1)
print(sum_mat)

[ 15  40  65  90 115]


In [6]:
sum_mat = np.sum(mat,axis = 0)
print(sum_mat)

[55 60 65 70 75]
