# 📝Assignment-2:

## 🎓Task 1:

In [38]:
import numpy as np
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [39]:
print("Sum: ",np.sum(arr))
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Std deviation: ",np.std(arr))

Sum:  210
Mean:  10.5
Median:  10.5
Std deviation:  5.766281297335398


In [40]:
indices = np.where(arr>10)[0]
print(indices)

[10 11 12 13 14 15 16 17 18 19]


## 🎓Task 2:

In [41]:
import numpy as np
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [42]:
arr1_transpose = np.transpose(arr1)
print(arr1_transpose)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [43]:
Row_sum_arr1 = np.sum(arr1,axis=0)
print(Row_sum_arr1)

[28 32 36 40]


In [44]:
Column_sum_arr1 = np.sum(arr1,axis=1)
print(Column_sum_arr1)

[10 26 42 58]


## 🎓Task 3:

In [50]:
import numpy as np

In [56]:
arr2 = np.random.randint(1,21, (3,3))
arr3 = np.random.randint(1,21, (3,3))

In [57]:
print("Addition: ",arr2+arr3)
print("Subtraction: ",arr2-arr3)
print("Multiplication: ",arr2*arr3)

Addition:  [[17  7 19]
 [11 23 26]
 [22 30 16]]
Subtraction:  [[ -5  -1   1]
 [ -3  13 -12]
 [-16   0   4]]
Multiplication:  [[ 66  12  90]
 [ 28  90 133]
 [ 57 225  60]]


In [58]:
dot_product = np.dot(arr2,arr3)
print(dot_product)

[[277 189 171]
 [303 211 420]
 [328 237 372]]


## 🎓Task 4:

In [59]:
arr4 = np.arange(1,13).reshape(3,4)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
mat = arr4[0:2,-2:]
print(mat)

[[3 4]
 [7 8]]
